### ISSUE TITLE
Build error with v1.2.1: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by kfrederix** [Elderjs/elderjs#102]
Hello!

First of all, thank you so much for Elder.js! Really love working with it!!
Since I was excited about the new release, I decided to try it out. But I am getting an error during build:
`TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined`

Seems to be coming from the dynamic require of ssr (in src/utils/svelteComponent.ts):
```
// eslint-disable-next-line import/no-dynamic-require
const ssrReq = require(ssr);
```

Not sure if this is caused by something on my local machine or not. Any ideas what I can do to fix this?

(The error also occurs with a clean install of latest Elderjs/template btw...)

**Comment by nickreese** [comment]
@kfrederix hmm. Interesting. Must be something different in the environments the template is working for me. 

I upgraded all the tests to cover windows but there may still be an edge-case I missed. 

I believe the error is originating in this file: https://github.com/Elderjs/elderjs/blob/master/src/partialHydration/prepareFindSvelteComponent.ts

Can you try logging stuff out there on your local install and see if we can turn up any clues?

**Comment by kfrederix** [comment]
Found the problem, I'll put up a PR with a fix... Feel free to edit the changes as you like, at least the PR should highlight exactly what goes wrong ;-)

**Comment by arggh** [comment]
I got this error on Mac OS Big Sur and the latest ElderJS, 1.3.1.

```
We see you want to load Home.svelte, but we don't see a compiled template in /Users/arggh/app/___ELDER___/compiled. You'll probably see more errors in a second. Make sure you've run rollup.
/ [
  TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
      at new NodeError (node:internal/errors:329:5)
      at validateString (node:internal/validators:129:11)
      at Module.require (node:internal/modules/cjs/loader:988:3)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.templateComponent (/Users/arggh/app/node_modules/@elderjs/elderjs/build/utils/svelteComponent.js:20:20)
      at buildPage (/Users/arggh/app/node_modules/@elderjs/elderjs/build/utils/Page.js:43:40)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
      at async Object.run (/Users/arggh/app/node_modules/@elderjs/elderjs/build/hooks/index.js:83:34)
      at async /Users/arggh/app/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:46:44
      at async processHook (/Users/arggh/app/node_modules/@elderjs/elderjs/build/utils/prepareRunHook.js:41:13) {
    code: 'ERR_INVALID_ARG_TYPE'
  }
]
```

**Comment by s-kris** [comment]
You need restart the dev

**Comment by MichaelEPope** [comment]
Just a note, in case somebody sees an error like this in the future, if oftentimes is caused by not naming your .svelte file correctly in a route.  If a route is named /product, you need to name the file Product.svelte.  If a route  is named /cat, the .svelte file needs to be named Cat.svelte.  I'm sure there is other cases where this error comes up, but that's one place to look.

**Comment by kookydev** [comment]
I was getting this issue because I imported a component that I wanted to hydrate-client without matching the .svelte name of the file. 
**For example:**
`import Functionality from './CarouselStaticFunctionality.svelte'` throws the above error and the build fails. (Although it works perfectly fine when you're not wanting to hydrate on the client) 
**Whereas:**
`import CarouselStaticFunctionality from './CarouselStaticFunctionality.svelte'` works fine for hydrating on the client.
