### ISSUE TITLE
Origin isn't being used to prefix the links

### ISSUE THREAD

**Issue by macabeus** [Elderjs/elderjs#120]
I'm developing a website to host on github pages, so I need to set a full address like `macabeus.github.io/ryujinx-catalog/` as the prefix for all links.

But even setting it on `elder.config.js` or `server.prefix` such as:
```js
module.exports = {
  origin: 'https://macabeus.github.io/ryujinx-catalog/',
```
```js
module.exports = {
  origin: 'https://macabeus.github.io/',
  server: {
    prefix: '/ryujinx-catalog',
```

It isn't being used to prefix any links. For instance, the builder generates `<link rel="stylesheet" href="/style.css"` instead of `<link rel="stylesheet" href="macabeus.github.io/ryujinx-catalog/style.css"`.

![image](https://user-images.githubusercontent.com/9501115/104806300-743d8380-57ce-11eb-803f-54f5ef53e004.png)

How to fix it?

**Edit**

Related: https://github.com/Elderjs/elderjs/issues/43

**Comment by jfowl** [comment]
I stumbled across this issue as well, while trying to use elderjs to generate a static page for gitlab pages.

Basically I get to store files under a domain like `https://jfowl.fspages.org/my-elderjs-site/`.
The current docs, as interpreted by me, suggest to adjust the config in the following way
```js
module.exports = {
  origin: 'jfowl.fspages.org/',
  [...]
  server: {
    prefix: 'my-elderjs-site/',
  },
}
```

when I run `npm run build` however, the prefix is not applied.
This is because most links are generated through `helpers.permalinks.someSiteThingy({slug: 'foo'})`.

According to https://github.com/Elderjs/elderjs/blob/master/src/utils/permalinks.ts#L10:
```ts
const permalinks = ({ routes, settings }) =>
  Object.keys(routes).reduce((out, cv) => {
    const prefix = settings.server && settings.server.prefix ? settings.server.prefix : '';
    // eslint-disable-next-line no-param-reassign
    out[cv] = (data) => `${prefix}${routes[cv].permalink({ request: data, settings })}`;
    return out;
  }, {});
```
it tries to pull the prefix from the server settings and prepend it to the url.

But!
https://github.com/Elderjs/elderjs/blob/master/src/Elder.ts#L84
```ts
this.settings.server = initialOptions.context === 'server' && this.settings.server;
```
during initialization, if the context isn't 'server', the server settings are gone.
Building however is always done with the context "build", so `settings.server === false` and the prefix disappears.

@nickreese was there a rationale behind not including the server's prefix in the build process?

**Comment by macabeus** [comment]
@jfowl I opened a PR fixing it. Maybe it could be useful for you

**Comment by nickreese** [comment]
@jfowl @macabeus In early versions of Elder.js there were checks against `settings.server` in a few places in the code that is why the `this.settings.server` is overwritten. 

I'm completely open to this refactor we just need to make sure things aren't breaking, especially plugins. 

More thoughts on the PR.

**Comment by nickreese** [comment]
@jfowl @macabeus I've included full implementation details in the PR. It is a bigger change than you'd think change because writing files to the right location is tricky, permalinks underpin the entire system, and there are edgecases in lots of areas. 

That said, if one of you tackles it I'm happy to review it.

**Comment by nickreese** [comment]
@jfowl @macabeus #128 should fix this issue.
