### ISSUE TITLE
News website

### ISSUE THREAD

**Issue by andreme** [Elderjs/elderjs#132]
Hi,

I'm evaluating elder.js as the site generator for a CMS build by me. We have a news website with 20k+ pages and limited dynamic content, so the concept of svelte/elder.js appeals to us.
I'm not familiar with svelte, so some of the questions might be off.
My interest is to find out how much effort it would be to add features that are missing, and I'm willing to do the work myself.

**Incremental build / caching**

I've read through https://github.com/Elderjs/elderjs/issues/8 , but my idea seems to be a bit different, I'll try to explain it here.
~~Generally, code/system changes are ignored, because the cache can be cleared in that case.~~
I would like to put a hook after the `data` hook that has the ability to compare the current request/data for a page(slug) with the request/data that was used in the previous build. If that hasn't changed, all further processing should be stopped.
The hash for the data could be stored in a .cache/pages/[deployId]/[slug].json (individual files due to parallel processing).

Now that I've thought about it, code/system changes could also be dealt with. There would be a global change id (git commit for example) that is written into the config. This id is also be stored in the .cache/pages/[deployId]/[slug].json. Then, the above hook knows to re-generate the page, even if the request/data has not changed. There would be another hook after `html`, that also skips further processing when the generated html has not changed.
This is important for me, because the files are uploaded to S3, and that's only necessary if they are changed.

There is another case where pages are deleted. It's not that important to me, but I'm sure there is a way to deal with that as well based on the slugs generated in allRequests.

**Questions**

1. Is it possible to have a hook stop the build process for a page?
2. Is/can the javascript code for components that are used on many pages extracted into external files? (Code splitting)
3. Is there a reason elder.js would not run in AWS Lambda (read-only filesystem, only /tmp and mounted directories writable)
4. I think it's possible to prevent writing output files into the filesystem by disabling elderWriteHtmlFileToPublic. What about files generated by plugins like the `images`?
5. I'm storing the files in S3, so I need to know all the files that are generated and deleted. Would it be possible to add a small virtual filesystem layer that is used by elder.js and the plugins like `images` to write output files, and can be intercepted by a hook?
6. Has the `images` plugin the ability to cache images already?

Thanks

**Comment by nickreese** [comment]
> I've read through #8 , but my idea seems to be a bit different, I'll try to explain it here.
Generally, code/system changes are ignored, because the cache can be cleared in that case.
I would like to put a hook after the data hook that has the ability to compare the current request/data for a page(slug) with the request/data that was used in the previous build. If that hasn't changed, all further processing should be stopped.
The hash for the data could be stored in a .cache/pages/[deployId]/[slug].json (individual files due to parallel processing).

The `data` hook runs after the route's `data()` function. You can definitely do this.

1. Yes, just disable the relevant hook (`elderWriteHtmlFileToPublic`) that Elder.js uses internally to write to a file and replace it with one that does what you want. 
2. This is done, yes. 
3. A few users use CF workers / Lambda functions. There is just no official guide on it. 
4. Plugins you would have to fork.
5. I am open to this and would be happy to review a PR.
6. Yes. It needs work, but yes.

**Comment by kiuKisas** [comment]
@andreme can we close this issue ?

**Comment by andreme** [comment]
Yes sorry, thanks @nickreese I've decided to go with a different system for now
