### ISSUE TITLE
<span>s around components

### ISSUE THREAD

**Issue by DenMesh** [Elderjs/elderjs#15]
Recently came across this project and loved the idea. However, when I tried to actually use it, I encountered some difficulties, addressed here and in another issue.

While rendering components Elder.js wraps them in <span>s. While have an idea or to as to the reasoning behind this decision, it would be great if the functionality was opt-in or at least allowed one to change the tag. Having a <span> wrap *the entire content* of a page just doesn't sit well with me.

**Comment by nickreese** [comment]
@DenMesh This is something we’ve grappled with and are still looking for a great solution to. 

Basically the problem is that it is possible to have inline components and block components and without inspecting the html returned by a Svelte component (svelte components can have multiple roots) there isn’t an easy way to know which is which. 

Span was used as div was breaking icons. 

I know in the push to get Elder.js open sourced this issue wasn’t addressed and it is still on our internal ticket tracker. 

We’re open to ideas. Even a div with a display inline may be a better solution.

**Comment by nickreese** [comment]
@DenMesh I've got a WIP PR to fix this issue. By default SSR'd components won't have a wrapping div or span now. Components that are hydrated will have a wrapping div and we may add support for inline components as well but it may be overkill as that could be done with css by the user. 

Here is the WIP PR is here: https://github.com/Elderjs/elderjs/pull/17
