### ISSUE TITLE
When passing data from the route to app with hydrate-client option all markdown data gets added

### ISSUE THREAD

**Issue by floratmin** [Elderjs/elderjs#160]
I tried to make a webpage with a hydrated app having hash-based routing. But as soon I set the `hydrate-client={{data}}` option, not only the data which I append gets added, but also all the markdown data from the template. So I have to create a new object on the static page and pass this object to the routes object, otherwise, all the markdown data gets added to the generated static HTML file.

I created a repository to highlight the problem (the first branch shows how to circumvent the problem):
https://github.com/floratmin/template/tree/routes
https://github.com/floratmin/template/tree/routes-markdown

**Comment by kiuKisas** [comment]
I just had a quick look into your code and it seems you used the `@elderjs/plugin-markdown` set to the routes `blog`, which will add your pages markdown to `data` on these routes. This is the expected behavior in order to generate your blog pages. 

What I propose you to do is to add an object into your `data` (in `route.js`), something like `hydratate` and put all the data you need for your hydrate component inside it, then pass this object. I guess is always better to separate what you need for SSG and hydrate component.

**Comment by floratmin** [comment]
Sorry if I was not totally clear. The route of concern is the app route (e.g. /en/app). The rest of the repo is the standard elder.js template. I am not intending to use the `@elderjs/plugin-markdown` in my project at all. I stumbled over this behaviour and this could add bloat to parts of the webpage where route data is passed to hydrated clients.

**Comment by nickreese** [comment]
@floratmin that is the designed behavior. You should only hydrate the absolute minimum so you’ll want to restructure the data object if the whole page needs to be hydrated. It is a different setup than a SPA.

**Comment by floratmin** [comment]
Thank you very much.
