### ISSUE TITLE
Component styles not added to cssStack

### ISSUE THREAD

**Issue by Hornebom** [Elderjs/elderjs#34]
I have the following issue: 
If a component is rendered conditionally and/or not initially, all its related css is not added to the cssStack. 

```
<script>
  import Button from '../Button/Button.svelte'
  let foo
</script>

<div>
  {#if foo}
    <Button>Click</Button>
  {/if}
</div>
```

The same issue is true when using the following loop
```
<script>
  import Button from '../Button/Button.svelte'
  let items
</script>

{#each items as item}
  <Button>Click</Button>
{/each}
```

The components html is rendered fine. Also the classes are in place and have unique hash. And the parent component has `hydrate-client={{ }}` set.
How can I make sure the css for conditionally rendered components will be added to the `cssStack`?

**Comment by nickreese** [comment]
@Hornebom Hmm, great question. 

The core problem is that the CSS isn't getting emitted during the SSR version of the Svelte component.  The Svelte compiler is trying to be helpful here removing any unwanted CSS. 

This is likely happening because the SSR component is missing props for `foo` or `items`.

Have you tried setting `hydrate-client={{foo}}` or `hydrate-client={{items}}`?

This should allow the SSR version to have the same data the client will be mounted with and you can avoid this issue.

If you need classes set that aren't going to be executed on the SSR component, I recommend you look at using Svelte's `:global()`.

Try the hydrate option first and let me know if you get the results you were expecting.

**Comment by Hornebom** [comment]
@nickreese Thanks for that tip

> The core problem is that the CSS isn't getting emitted during the SSR version of the Svelte component. The Svelte compiler is trying to be helpful here removing any unwanted CSS.

A bit too helpful 😅

I solved it for now by setting svelte compile css option to `true`. As documented here https://svelte.dev/docs#svelte_compile
Probably I have to deal with the performance drawbacks for now
