### ISSUE TITLE
Templates need unique compile paths to fix conflicts

### ISSUE THREAD

**Issue by jbmoelker** [Elderjs/elderjs#41]
The Rollup configuration has the same target directory for different Svelte source directories. This causes conflicts when source templates in different directories have the same name.

All these Svelte templates:
* `src/components/Example/Example.svelte`
* `src/routes/example/Example.svelte`
* `src/layouts/Example.svelte`

Compile to the same output:
* `__ELDER__/compiled/Example.js`

Maybe change this into `__ELDER__/svelte/components/Example.js` etc?
(as I can imagine you also want to compile `src/routes/:route/route.js` to `__ELDER__/routes/:route.js` in the future).

**Comment by bbuhler** [comment]
Hi @nickreese,

I am migrating a project from a sapper code base with a few components that have the same name in different folders which leads to the same conflicts.

For Example:
- `src/components/variantA/Button.svelte`
- `src/components/variantB/Button.svelte`
- `src/components/variantC/Button.svelte`

I guess it's due to the folder structures are been flattened.
