### ISSUE TITLE
Support hydrated components in IE11

### ISSUE THREAD

**Issue by jbmoelker** [Elderjs/elderjs#45]
As a static site generator Elder is very well suited for legacy browsers. However hydrated components don't work in Internet Explorer yet for a couple of reasons:

* the inlined SystemJS loader invocation needs to be in ES5.
* IE11 requires a polyfill for `Promise` and `fetch` (SystemJS needs them).
* IE11 requires Svelte components to be compiled to ES5.

**SystemJS loader in ES5**
The [SystemJS loader invocation is currently in ES6](https://github.com/Elderjs/elderjs/blob/master/src/utils/svelteComponent.ts#L113-L118):
```js
const clientJs = `
System.import('${clientSrc}').then(({ default: App }) => {
  new App({
    target: document.getElementById('${cleanComponentName.toLowerCase()}-${id}'),
    hydrate: true,
    props: ${devalue(props)}
  });
});
`
```
This code isn't passed through Rollup, so should just be in ES5:
```js
const clientJs = `
System.import('${clientSrc}').then(function(importedModule) {
  var App = importedModule.default;
  new App({
    target: document.getElementById('${cleanComponentName.toLowerCase()}-${id}'),
    hydrate: true,
    props: ${JSON.stringify(props)}
  });
});
`
```
**IE11 requires a polyfill for `Promise` and `fetch`**
[Elder already conditionally polyfills `IntersectionObserver`](https://github.com/Elderjs/elderjs/blob/15fa092ae9a41abc3d4e815cb86ee05f5e6b67e6/src/hooks.ts#L201-L205):
```html
<script>
if (!('IntersectionObserver' in window)) {
  var script = document.createElement("script");
  script.src = "/static/intersection-observer.js";
   document.getElementsByTagName('head')[0].appendChild(script);
};
</script>
```
The same strategy could be used for `Promise` and `fetch`:
```html
<script>
(function() {
  function polyfill (feature, src) {
    if (feature in window) return;
     var script = document.createElement('script');
     script.src = src;
     document.head.appendChild(script);
  }
  polyfill('Promise', '/static/promise-polyfill.js');
  polyfill('fetch', '/static/unfetch.js');
  polyfill('IntersectionObserver', '/static/intersection-observer.js');
}());
</script>
```
I think this would be good lightweight polyfill candidates: [`promise-polyfill`](https://www.npmjs.com/package/promise-polyfill) (<1kb) and [`unfetch`](https://www.npmjs.com/package/unfetch) (500b).

Side note: I would be a big fan of moving all files generated by Elder (polyfills, Svelte components, ...) to `${distDir}/_elder` (just like `dist/_nuxt`) and have their names revision hashed (like is already done with Svelte components) so that directory can easily and aggressively be cached.

**IE11 requires Svelte components to be compiled to ES5**
Probably the hardest part to configure. [Elder already uses Babel in its Rollup config](https://github.com/Elderjs/elderjs/blob/15fa092ae9a41abc3d4e815cb86ee05f5e6b67e6/src/utils/getRollupConfig.ts#L59-L64). Perhaps IE11 support can be added using `babel/preset-env` like [Sapper is doing in its Rollup config for legacy browsers](https://github.com/sveltejs/sapper-template/blob/rollup/rollup.config.js#L39-L54).

I don't have a working setup yet. I'm posting this here as I hope this well help. Maybe this could be part of #42?

**Comment by nickreese** [comment]
@jbmoelker Definitely a fan of coming up with a plan for legacy browsers. 👍 

My hope was to include a robust plan including module/nomodule support but it has turned out to be a major rabbit hole. I've included my learning below and currently am leaning towards offering an either/or solution on #42 where the user can opt into using modules for the reasons outlined below.

I do believe module/nomodule to be a better solution than either/or, but after 20+ hours thus far on this issue I can't commit to personally developing this out over the next 3 months due to limited dev time. I'm 100% happy to review PRs and even hop on discord/zoom and discuss implementations. 

## Short term

In the short term I'm 100% open to polyfilling as needed and would like to implement a `legacy:true` in the `elder.config.js` as shown in #42 so that users can opt into using modules. (we'd need to add whatever polyfills chosen to peer deps)

Feel free to add those changes to that PR. 

## Learnings from Module/NoModule

At the surface, module/nomodule seems like an easy implementation. I thought it would be as easy as **if this browser supports import, use modules, if not don't**.

That said, having spend significant time on browser stack, and trying the [solutions proposed](https://jasonformat.com/modern-script-loading/) [by several guides](https://hospodarets.com/native-ecmascript-modules-dynamic-import) [on module loading](https://hospodarets.com/native-ecmascript-modules-nomodule), there isn't an implementation I can't find supports mounting the components directly in the html, instead we have to write separate mount code for `module` and `nomodule` to route specific files. Meaning that if the route `/foo/bar/` hydrates a component we need to write `/foo/bar/module.js` and `/foo/bar/legacy.js` to the `distDir`.

This is the only solution I've found because of the old browsers choke on the unknown syntax.

Now I may be missing a potential solution (`try/catch` with an `eval` on each component or something) that allows us to mount the components directly in the html, but if I'm not I think the refactor would be a huge breaking one so I'm more inclined to offer an either/or solution until a major version update. 

### Other issues:

1. sapper and most other implementations I've found do feature detection using using `eval` or `new Function`. I'm pretty new to legacy browser support and polyfills in general, but this seems more than a little hacky and can cause issues with security policies. 
1. If module/nomodule is implemented, I think the `beforeHydrateStack`, `hydrateStack` and any new hooks with how Elder.js handles component mounting/hydrating should be removed from the `hookInterface`.
1. Offering module/nomodule causes us to bundle a total of 3 separate versions of each component. This can be sped up during dev, by excluding the nomodule version, but there is a noticeable slowdown in dev speed.
1. If we have to write 2 separate files for each page with hydrated components, suddenly we're producing a ton more files. Testing it on ElderGuide.com we went from ~20k files to almost ~55k files which would really impact deployment times but does allow for aggressive caching if we added a unique build ID to them. 



> Note: I also saw your issue of _elderjs intertwined above. We can discuss more thoroughly in another issue, but my concern with `_elderjs` is that I've seen things like db credentials get bundled by accident too often in route and layout svelte files. I went with the current `___ELDER___` outside of the public folder to keep users from leaking sensitive items. An option could be to add an `elderDir` relative to the project root but we should discuss that elsewhere.

**Comment by jbmoelker** [comment]
I think you're actually on the right track with the module/no module approach!

**module/no module bundles**

Yes, you are right that each hydrateable component ends up with a modern and legacy bundle. Nuxt.js does the exact same thing, with the same extra build times (my colleague wrote about that: https://www.voorhoede.nl/en/blog/faster-nuxt-sites-on-netlify/#serve-modern-bundles). And just like you mentioned, Nuxt.js only creates the legacy bundle during production builds and not during development.

Since `<script type="module">` and `IntersectionObserver` are both well supported by modern browsers, I think you could leave the `IntersectionObserver` polyfill and SystemJS out of that implementation and use native `IntersectionObserver` and `import()`'s.

Since `nomodule` is typically for ~1-2% of users (IE11), I think you can take some shortcuts: no `IntersectionObserver`, no SystemJS (meaning no `Promise` and `fetch` polyfills),  and just load those scripts synchronously:
```html
<div class="clock" id="clock-CtWDXfDzFx"> ... </div>
<!-- loads legacy bundle synchronously and exposes EntryClock on window.elder -->
<script nomodule src="/svelte/entryClock-dce54956.legacy.js"></script>
<script nomodule>new window.elder.EntryClock({ targetId: 'clock-CtWDXfDzFx', props: {} });</script>

<!-- another clock -->
<div class="clock" id="clock-AfgFiogfDf"> ... </div>
<!-- same script, but is already loaded (maybe compiler can leave out next line), so directly hydrates component -->
<script nomodule src="/svelte/entryClock-dce54956.legacy.js"></script>
<script nomodule>new window.elder.EntryClock({ targetId: 'clock-AfgFiogfDf', props: {} });</script>
```

**Babel config**

Yes you're right about automatically using `babel.config.js` file when present. But I think you want 2 bundles, 1 legacy, 1 modern. So inside of the Rollup config you'll want to use two adapted Babel configs I think. Not something I do on a daily basis either.

> sorry for the confusion on `_elder`/`__ELDER__`. `__ELDER__` in the root directory is fine. I meant put all the public compiled files into one `public/_elder` directory so there's no separate `public/svelte` and `public/static` directory. Can create a separate discussion for that :)

**Comment by nickreese** [comment]
@jbmoelker 

While I think the below code will work for `nomodule` we'll still need to write a file for `module` such as  `<script type="module" src="/foo/bar/module.js"></script>`.

```javascript
<div class="clock" id="clock-CtWDXfDzFx"> ... </div>
<!-- loads legacy bundle synchronously and exposes EntryClock on window.elder -->
<script nomodule src="/svelte/entryClock-dce54956.legacy.js"></script>
<script nomodule>new window.elder.EntryClock({ targetId: 'clock-CtWDXfDzFx', props: {} });</script>
```

## IIFE vs Systemjs

I believe the above example uses an `iife`. While this is great we don't get bundle splitting... but more importantly we still have to write the `props` received from`hydrate-client` to the HTML of the page. If we used `systemjs` we could write these `props` to each file individually for better caching.

If we use an `iife` I believe we can polyfill with babel instead of needing to manage our own polyfills. (maybe we can do this with System.js)


## Elder.js Changes 

Here is my understanding of the changes required.

### `rollup.config.js` (`getRollupConfig`)

1. We add another config using `systemjs` or `iife`. (discussion above)
1. We need to create a babel config targeting IE11 that Elder.js can use internally. 
1. The new `iife` config would use our own polyfill'd ready babel that is targeted at IE11. 
1. If a user wants babel on the `module` version the just need to define it and we let the rollup babel plugin grab it.

#### `Elder.ts`

1. Add a unique build id to the settings object. (this will be used in hashing the `${permalink}${buildId}-module.js`)

### Broader Changes

These changes are mainly in `Page.ts`, `svelteComponent.ts`, `getHashedSvelteComponent`, `hooks.ts`
1. We add a `legacyStack` in`Page.ts`;
1. Update `getHashedSvelteComponent.ts` to look for the `iife` for the `nomodule` output.
1. We move the `props` from `hydrate-client` to a `window.___elderjs___.${uniqueComponentId}Props` so they can be referenced by both `module` and `nomodule`.
1. When a component is hydrated in `svelteComponent` we push the legacy code to `legacyStack` and module code to `hydrateStack`. We need to determine the code that will be used for each.
1. Where `Page.ts` [compiles the stacks](https://github.com/Elderjs/elderjs/blob/a3fcf6a0b713b67a0830d52e1e0f8469e9848959/src/utils/Page.ts#L79) we now write a file including the `${permalink}/${buildId}-module.js` if needed.


### Open questions:
1. Look into how we can not hydrate two `nomodule` scripts. I believe if we used two separate entries in `legacyStack` one for loading`<script nomodule src="/svelte/entryClock-dce54956.legacy.js"></script>` and another for actually mounting it `<script nomodule>new window.elder.EntryClock({ targetId: 'clock-AfgFiogfDf', props: {} });</script>` the duplicate entries should be removed by `processStacks`. (If we also set a `priority` in each stack entry we can ensure what order they are output to the page.)
1. I'm still not sure how we'll ensure only browsers that need the legacy bundle will get it. Below I've included how Sapper does it for reference.

```
(function () {
  try {
    eval('async function x(){}');
    var main = '/client/client.d7c1d2c3.js';
  } catch (e) {
    main = '/client/legacy/client.c6d7adeb.js';
  }
  var s = document.createElement('script');
  try {
    new Function("if(0)import('')")();
    s.src = main;
    s.type = 'module';
    s.crossOrigin = 'use-credentials';
  } catch (e) {
    s.src = '/client/shimport@1.0.1.js';
    s.setAttribute('data-main', main);
  }
  document.head.appendChild(s);
})();
```

**Comment by nickreese** [comment]
Made some progress on this with the help from a private JS discord thanks to @swyx. 

Got a PoC that allows for polyfilled iife generation and modules when supported without generating new bundles for each page.

**Comment by nickreese** [comment]
So I said I wasn't going to work on this but I spent a bit of time getting a PoC real `module/nomodule` fallback working in between a litany of phone calls today.

It doesn't support shared stores in the nomodule fallback. #44 

Please check it out on this #42.
