### ISSUE TITLE
Ability to disable hook on a route level

### ISSUE THREAD

**Issue by talha-asad** [Elderjs/elderjs#62]
Is there a way currently to disable a hook on a route level as opposed to app wide? If not, is this something you'd be interested in supporting in the future?

**Comment by nickreese** [comment]
@talha-asad Do you have a usecase in mind? 

I think this would only be required on core hooks. All other hooks could be managed by checking `request.route` and matching on that. 

Early versions of Elder.js had the idea of hooks at the route level but our team found those to just spread complexity into multiple places instead of pushing it all to one main file everyone would expect it to be in.

**Comment by nickreese** [comment]
To be clear, any function registered on a hook could check the `request.route` and only mutate props when desired.

**Comment by nickreese** [comment]
@talha-asad going to close this issue. Let me know if you need help implementing the above.
