### ISSUE TITLE
CSS Sourcemap

### ISSUE THREAD

**Issue by armchair-traveller** [Elderjs/elderjs#66]
How would I get CSS sourcemaps to work with DevTools > Sources > Filesystem? I don't really know Rollup options as you can probably tell, but as I understand there's the Replacements section in the docs which serves this purpose. What isn't clear to me is if it's just a placeholder name or if that's exactly what you need to type in to change the Rollup config. There's no mention of how to get this specific feature working, or if it's even remotely possible.

I tried adding `sourceMap: true` to `svelte.config.js` but maybe that's completely unrelated.

Also, I'm wondering if anyone even uses sourcemaps since I've only seen brief mention of it in documentation on Rollup.

**Comment by nickreese** [comment]
Replacements are for string replacements. (Needs documentation)

Imm honestly not well versed in source amps but pretty sure because of how we are emitting the css directly to the head of the page we aren’t able to display the source map... If I’m wrong let me know, it could be added to the roadmap.
