### ISSUE TITLE
Elderjs v1.1.6 svelte static components style not compiled on windows

### ISSUE THREAD

**Issue by meigo** [Elderjs/elderjs#84]
With elderjs v1.1.6 on windows styles from svelte components don't make it to the final css.

Output of HookDetail.svelte:

![style](https://user-images.githubusercontent.com/230715/97796753-a4897300-1c1e-11eb-9fbb-395b190c0cbe.jpg)

**Comment by nickreese** [comment]
@meigo gah! Cross platform separators at play again. Can you test changing this line to include `path.sep` Instead of the trailing slash in your local version of Elder.js?

https://github.com/Elderjs/elderjs/blob/7df0a727c4dbf8307c389f25c2ceb72d134e3b67/src/utils/rollupPluginHandleCss.ts#L30

There may be other cross platform issue but they should be localized in this file.

**Comment by thisislawatts** [comment]
@nickreese worth setting up a GitHub CI runner to execute tests on Windows ie. `runs-on: windows-latest`?
https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

Although maybe there's an eslint rule that could help catch these?

**Comment by nickreese** [comment]
@thisislawatts Great idea, never setup a runner but we can definitely look into it.  cc: @halafi

**Comment by meigo** [comment]
>  Can you test changing this line to include path.sep Instead of the trailing slash in your local version of Elder.js?
 
Yes, that fixes it, thanks Nick!

**Comment by nickreese** [comment]
@meigo Pushed in v1.1.7
