### ISSUE TITLE
Add html attributes into stacks hook

### ISSUE THREAD

**Issue by kiuKisas** [Elderjs/elderjs#93]
Hey, me again.
During my i18n plugin journey, I was digging into the best way to implement the dynamic lang attribute.

As discussed in #87, the current way to do it is to edit `htmlString` in a `compileHtml` hook by overwriting and disabling the hook in `elder.config.js`.

So I currently have 2 choices:
- let the user add it himself if he wants to. It's the way I go for now. but I feel like it should be manage by the i18n plugin.
- an option to overwriting `htmlString` by the plugin. However, the user will still need to disabled the elder hook, and if I understand proberly, couldn't use this hook anymore without rewriting the entire htmlString an disabled this i18n option.

Currently working with the stacks hooks to add some elements to `headStack`, I was wondering if we can add an `htmlAttributesStack` in the same way the headStack exist. This way, we can manage a dynamic lang attribute while letting the user adding other html attributes , and still overwriting `compileHtml` if he wants to without breaking anything.

 🔜 If it's something that seems relevant to you, I'm ok to make a PR with this feature. (I'm curious to see how elderjs work internally btw)

 ❓In this context, maybe we should re-consider adding a `lang` option in `elder.config.js` (but keep `en` by default) as it would become "dynamic" in a stack of attributes anyway; it will also feel less arbitrary (in the case of a non-english website).

 ❓Also, if we do that, should we also add a `bodyAttributesStack` to cover most of use cases to let plugins adding data while keeping the default `compileHtml` hook most of the time ?

**Comment by nickreese** [comment]
@kiuKisas This sounds like a good approach. Let's just make sure we cover the new functionality with tests and documented. I'd also add the least amount of new functionality as possible because each change we make further extends the api surface. 

Notes to help guide you on the PR.

1. Adding a stack is a bit involved. You'll need to add an empty array in `Page.ts`, you'll need to run `page.htmlAttributesStack = page.processStack("htmlAttributesStack")` near where the other stacks are processed (that creates a string out of the stack), and then make sure that `htmlAttributesStack` is available in the `props` and `mutable` arrays of the hooks it should be edited on.
1. In the internal hooks file, we'll need to update `elderCompileHtml` to use `htmlAttributesStack`
1. Adding `lang` to `elder.config.js`. See `validations.ts`. Note that the `label` field in that file is used to generate the docs. You can set the default to `en` there. You'll also need to push this value on to the `htmlAttributesStack` in the `Page.ts` file.
